<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsertPicturesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pictures')->insert([
            [
                'id' => 1,
                'folder' => '/pictures/',
                'name' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'cover' => true,
                'alt' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 1,
            ],
            [
                'id' => 2,
                'folder' => '/pictures/',
                'name' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 1,
            ],[
                'id' => 3,
                'folder' => '/pictures/',
                'name' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 1,
            ],[
                'id' => 4,
                'folder' => '/pictures/',
                'name' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 1,
            ],[
                'id' => 5,
                'folder' => '/pictures/',
                'name' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'fc26eb10-ee19-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 1,
            ],
            [
                'id' => 6,
                'folder' => '/pictures/',
                'name' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'cover' => true,
                'alt' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 2,
            ],
            [
                'id' => 7,
                'folder' => '/pictures/',
                'name' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 2,
            ],[
                'id' => 8,
                'folder' => '/pictures/',
                'name' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'dccd82b6-f03e-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 2,
            ],[
                'id' => 9,
                'folder' => '/pictures/',
                'name' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 2,
            ],[
                'id' => 10,
                'folder' => '/pictures/',
                'name' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'cover' => false,
                'alt' => 'caa61f3a-f03e-11eb-9a03-0242ac130003.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 2,
            ],[
                'id' => 11,
                'folder' => '/pictures/',
                'name' => 'maisonville.jpg',
                'cover' => true,
                'alt' => 'maisonville.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 3,
            ],[
                'id' => 12,
                'folder' => '/pictures/',
                'name' => 'maisonville.jpg',
                'cover' => false,
                'alt' => 'maisonville.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 3,
            ],[
                'id' => 13,
                'folder' => '/pictures/',
                'name' => 'haussman.jpg',
                'cover' => true,
                'alt' => 'haussman.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 4,
            ],[
                'id' => 14,
                'folder' => '/pictures/',
                'name' => 'haussman.jpg',
                'cover' => false,
                'alt' => 'haussman.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 4,
            ],[
                'id' => 15,
                'folder' => '/pictures/',
                'name' => 'chateau.jpg',
                'cover' => true,
                'alt' => 'chateau.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 5,
            ],[
                'id' => 16,
                'folder' => '/pictures/',
                'name' => 'borddemer.jpg',
                'cover' => true,
                'alt' => 'borddemer.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 6,
            ],[
                'id' => 17,
                'folder' => '/pictures/',
                'name' => 'ancienne.jpg',
                'cover' => true,
                'alt' => 'ancienne.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 7,
            ],[
                'id' => 18,
                'folder' => '/pictures/',
                'name' => 'garage.jpg',
                'cover' => true,
                'alt' => 'garage.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 8,
            ],[
                'id' => 19,
                'folder' => '/pictures/',
                'name' => 'terrain.jpg',
                'cover' => true,
                'alt' => 'terrain.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 9,
            ],[
                'id' => 20,
                'folder' => '/pictures/',
                'name' => 'parking.jpg',
                'cover' => true,
                'alt' => 'parking.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 10,
            ],[
                'id' => 21,
                'folder' => '/pictures/',
                'name' => 'commerce.jpg',
                'cover' => true,
                'alt' => 'commerce.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 11,
            ],[
                'id' => 22,
                'folder' => '/pictures/',
                'name' => 'paturage.jpg',
                'cover' => true,
                'alt' => 'paturage.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 12,
            ],[
                'id' => 23,
                'folder' => '/pictures/',
                'name' => 'localpro.jpg',
                'cover' => true,
                'alt' => 'localpro.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 13,
            ],[
                'id' => 24,
                'folder' => '/pictures/',
                'name' => 'epicerie.jpg',
                'cover' => true,
                'alt' => 'epicerie.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 14,
            ],[
                'id' => 25,
                'folder' => '/pictures/',
                'name' => 'stockage.jpg',
                'cover' => true,
                'alt' => 'stockage.jpg',
                'created_at' => '2021-07-26 16:18:00',
                'updated_at' => null,
                'id_estate' => 15,
            ],
        ]);
    }
}
