<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsertPicturesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pictures')->insert([
            [
                'id' => 1,
                'folder' => '/estates/',
                'name' => 'estate_id_1_1.jpg',
                'cover' => false,
                'alt' => 'Salon d\'un appartement de centre ville',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 1,
            ],
            [
                'id' => 2,
                'folder' => '/estates/',
                'name' => 'estate_id_1_2.jpg',
                'cover' => false,
                'alt' => 'Belle chambre spacieuse',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 1,
            ],[
                'id' => 3,
                'folder' => '/estates/',
                'name' => 'estate_id_1_3.jpg',
                'cover' => true,
                'alt' => 'Table a manger',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 1,
            ],[
                'id' => 4,
                'folder' => '/estates/',
                'name' => 'estate_id_2_1.jpg',
                'cover' => false,
                'alt' => 'Salle de bain moderne',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 2,
            ],[
                'id' => 5,
                'folder' => '/estates/',
                'name' => 'estate_id_2_2.jpg',
                'cover' => true,
                'alt' => 'Canapé',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 2,
            ],
            [
                'id' => 6,
                'folder' => '/estates/',
                'name' => 'estate_id_2_3.jpg',
                'cover' => false,
                'alt' => 'Petite cuisine',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 2,
            ],
            [
                'id' => 7,
                'folder' => '/estates/',
                'name' => 'estate_id_3_1.jpg',
                'cover' => false,
                'alt' => 'Grande cuisine moderne',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 3,
            ],[
                'id' => 8,
                'folder' => '/estates/',
                'name' => 'estate_id_3_2.jpg',
                'cover' => true,
                'alt' => 'Etagère',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 3,
            ],[
                'id' => 9,
                'folder' => '/estates/',
                'name' => 'estate_id_3_3.jpg',
                'cover' => false,
                'alt' => 'Séjour',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 3,
            ],[
                'id' => 10,
                'folder' => '/estates/',
                'name' => 'estate_id_4_1.jpg',
                'cover' => true,
                'alt' => 'Salon appartement blanc et noir',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 4,
            ],[
                'id' => 11,
                'folder' => '/estates/',
                'name' => 'estate_id_4_2.jpg',
                'cover' => false,
                'alt' => 'Cuisine appartement blanc et noir',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 4,
            ],[
                'id' => 12,
                'folder' => '/estates/',
                'name' => 'estate_id_4_3.jpg',
                'cover' => false,
                'alt' => 'Salle de bain',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 4,
            ],[
                'id' => 13,
                'folder' => '/estates/',
                'name' => 'estate_id_5_1.jpg',
                'cover' => false,
                'alt' => 'Maison ancienne',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 5,
            ],[
                'id' => 14,
                'folder' => '/estates/',
                'name' => 'estate_id_5_2.jpg',
                'cover' => true,
                'alt' => 'Chateau de Montmirail',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 5,
            ],[
                'id' => 15,
                'folder' => '/estates/',
                'name' => 'estate_id_6_1.jpg',
                'cover' => true,
                'alt' => 'Maison en bord de mer',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 6,
            ],[
                'id' => 16,
                'folder' => '/estates/',
                'name' => 'estate_id_6_2.jpg',
                'cover' => false,
                'alt' => 'Beau salon spacieux',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 6,
            ],[
                'id' => 17,
                'folder' => '/estates/',
                'name' => 'estate_id_6_3.jpg',
                'cover' => false,
                'alt' => 'Fauteuil au soleil',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 6,
            ],[
                'id' => 18,
                'folder' => '/estates/',
                'name' => 'estate_id_7_1.jpg',
                'cover' => true,
                'alt' => 'Maison ancienne',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 7,
            ],[
                'id' => 19,
                'folder' => '/estates/',
                'name' => 'estate_id_7_2.jpg',
                'cover' => false,
                'alt' => 'Canapé ancien',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 7,
            ],[
                'id' => 20,
                'folder' => '/estates/',
                'name' => 'estate_id_7_3.jpg',
                'cover' => false,
                'alt' => 'Buffet de cuisine',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 7,
            ],[
                'id' => 21,
                'folder' => '/estates/',
                'name' => 'estate_id_8_1.jpg',
                'cover' => true,
                'alt' => 'Garage',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 8,
            ],[
                'id' => 22,
                'folder' => '/estates/',
                'name' => 'estate_id_9_1.jpg',
                'cover' => true,
                'alt' => 'Terrain constructible',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 9,
            ],[
                'id' => 23,
                'folder' => '/estates/',
                'name' => 'estate_id_10_1.jpg',
                'cover' => true,
                'alt' => 'Parking sous-terrain',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 10,
            ],[
                'id' => 24,
                'folder' => '/estates/',
                'name' => 'estate_id_11_1.jpg',
                'cover' => true,
                'alt' => 'Façade de local d\'un magasin',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 11,
            ],[
                'id' => 25,
                'folder' => '/estates/',
                'name' => 'estate_id_12_1.jpg',
                'cover' => true,
                'alt' => 'Champ de paturage',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 12,
            ],[
                'id' => 26,
                'folder' => '/estates/',
                'name' => 'estate_id_13_1.jpg',
                'cover' => true,
                'alt' => 'Local professionel',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 13,
            ],[
                'id' => 27,
                'folder' => '/estates/',
                'name' => 'estate_id_14_1.jpg',
                'cover' => true,
                'alt' => 'Studio',
                'created_at' => now(),
                'updated_at' => null,
                'id_estate' => 14,
            ],
        ]);
    }
}
